name: Development

on:
  push:
    branches-ignore:
      - master
      - main

jobs:
  test_default:
    name: Test default TeaStore
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: |
          mvn clean install
          cd tools/ && ./build_docker.sh && cd ..
          sed -i 's/descartesresearch\///g' examples/docker/docker-compose_default.yaml
          docker-compose -f examples/docker/docker-compose_default.yaml up -d
          echo "Waiting 2 minutes for TeaStore to start." ; sleep 120
          ./tools/test_webui.sh localhost http 8080
          docker-compose -f examples/docker/docker-compose_default.yaml down
  test_https:
    name: Test HTTPS TeaStore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: |
          mvn clean install
          cd tools/ && ./build_docker.sh && cd ..
          sed -i 's/descartesresearch\///g' examples/docker/docker-compose_https.yaml
          docker-compose -f examples/docker/docker-compose_https.yaml up -d
          echo "Waiting 2 minutes for TeaStore to start." ; sleep 120
          ./tools/test_webui.sh localhost https 8443
          docker-compose -f examples/docker/docker-compose_https.yaml down
  test_kieker:
    name: Test TeaStore with Kieker monitoring
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: |
          mvn clean install
          cd tools/ && ./build_docker.sh && cd ..
          sed -i 's/descartesresearch\///g' examples/docker/docker-compose_kieker.yaml
          sed -i 's/descartesresearch\///g' examples/docker/docker-compose_rabbitmq.yaml
          docker-compose -f examples/docker/docker-compose_rabbitmq.yaml up -d
          echo "Waiting 2 minutes for RabbitMQ to start." ; sleep 120
          docker-compose -f examples/docker/docker-compose_kieker.yaml up -d
          echo "Waiting 2 minutes for TeaStore to start." ; sleep 120
          ./tools/test_webui.sh localhost http 8080
          ./tools/test_kieker.sh localhost 8081
          docker-compose -f examples/docker/docker-compose_kieker.yaml down
          docker-compose -f examples/docker/docker-compose_rabbitmq.yaml down
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          mvn clean install
          cd tools/ && ./build_docker.sh && cd ..
          sed -i 's/descartesresearch\///g' examples/docker/docker-compose_default.yaml
          docker-compose -f examples/docker/docker-compose_default.yaml up -d
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: e2e-tests
          wait-on: http://localhost:8080
          wait-on-timeout: 120
      - name: Cleanup docker
        run: docker-compose -f examples/docker/docker-compose_default.yaml down --volumes --remove-orphans
        if: ${{ always() }}
  build:
    name: Build and publish Docker images of TeaStore
    runs-on: ubuntu-latest
    needs: [test_default, test_https, test_kieker,cypress-run]
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: |
          mvn clean install -DskipTests
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=${GIT_BRANCH}"
          echo "GIT_BRANCH=${GIT_BRANCH}" >> ${GITHUB_ENV}
          sed -i "s/teastore-base:latest/teastore-base:${GIT_BRANCH}/g" services/tools.descartes.teastore.auth/Dockerfile
          sed -i "s/teastore-base:latest/teastore-base:${GIT_BRANCH}/g" services/tools.descartes.teastore.image/Dockerfile
          sed -i "s/teastore-base:latest/teastore-base:${GIT_BRANCH}/g" services/tools.descartes.teastore.persistence/Dockerfile
          sed -i "s/teastore-base:latest/teastore-base:${GIT_BRANCH}/g" services/tools.descartes.teastore.recommender/Dockerfile
          sed -i "s/teastore-base:latest/teastore-base:${GIT_BRANCH}/g" services/tools.descartes.teastore.registry/Dockerfile
          sed -i "s/teastore-base:latest/teastore-base:${GIT_BRANCH}/g" services/tools.descartes.teastore.webui/Dockerfile
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-base
          file: utilities/tools.descartes.teastore.dockerbase/Dockerfile
          path: utilities/tools.descartes.teastore.dockerbase
          tags: ${{ env.GIT_BRANCH }}
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-recommender
          file: services/tools.descartes.teastore.recommender/Dockerfile
          path: services/tools.descartes.teastore.recommender
          tags: ${{ env.GIT_BRANCH }}
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-webui
          file: services/tools.descartes.teastore.webui/Dockerfile
          path: services/tools.descartes.teastore.webui
          tags: ${{ env.GIT_BRANCH }}
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-image
          file: services/tools.descartes.teastore.image/Dockerfile
          path: services/tools.descartes.teastore.image
          tags: ${{ env.GIT_BRANCH }}
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-auth
          file: services/tools.descartes.teastore.auth/Dockerfile
          path: services/tools.descartes.teastore.auth
          tags: ${{ env.GIT_BRANCH }}
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-persistence
          file: services/tools.descartes.teastore.persistence/Dockerfile
          path: services/tools.descartes.teastore.persistence
          tags: ${{ env.GIT_BRANCH }}
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-registry
          file: services/tools.descartes.teastore.registry/Dockerfile
          path: services/tools.descartes.teastore.registry
          tags: ${{ env.GIT_BRANCH }}
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-db
          file: utilities/tools.descartes.teastore.database/Dockerfile
          path: utilities/tools.descartes.teastore.database
          tags: ${{ env.GIT_BRANCH }}
      - uses: jerray/publish-docker-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: descartesresearch/teastore-kieker-rabbitmq
          file: utilities/tools.descartes.teastore.kieker.rabbitmq/Dockerfile
          path: utilities/tools.descartes.teastore.kieker.rabbitmq
          tags: ${{ env.GIT_BRANCH }}
